var n1 = prompt("Ingrese un primer número entero a restar: ")
n1 = parseInt(n1)
console.log(n1)
var n2 = prompt("Ingrese un segundo número entero a restar: ")
n2 = parseInt(n2)
console.log(n2)
alert("la resta es : " + (n1-n2))